# GENERAL-INPUT CHANGE FREELY 
# paths always with "/" at the end!
# PATH TO THE BAM FILES!
input: /home/operator/Downloads/cnvs_cholestasis/samples/

output: /home/operator/Downloads/cnvs_cholestasis/

refgenome:
   ref_dir: /home/operator/InterOmics/workflows/interomics_snakemake/reference/
   ref: /home/operator/InterOmics/workflows/interomics_snakemake/reference/GRCh38_character_genome.fasta
   bed: /home/operator/InterOmics/workflows/interomics_snakemake/reference/SureSelectXT_Human_All_Exon_V7.bed
   interval: /home/operator/InterOmics/workflows/interomics_snakemake/reference/SureSelectXT_Human_All_Exon_V6+UTRs.interval_list
   #SureSelectXT_Human_All_Exon_V6+UTRs.interval_list
   dict: /home/operator/InterOmics/workflows/interomics_snakemake/reference/GRCh38_character_genome.dict
   known_var: /home/operator/InterOmics/workflows/interomics_snakemake/reference/dbsnp_156_chr.vcf.gz
   data_source: /home/operator/InterOmics/workflows/interomics_snakemake/data_source/funcotator_germline
   map: /home/operator/InterOmics/workflows/interomics_snakemake/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.r101.s501.blacklist
   gnomad_sv: /home/operator/InterOmics/workflows/interomics_snakemake/reference/gnomad.v4.1.sv.sites.vcf
   gtf: /home/operator/InterOmics/workflows/interomics_snakemake/reference/Homo_sapiens.GRCh38.109.gtf.gz
   annotsvdb: /home/operator/cariotipagem/VKaryo/reference/AnnotSV_DB


